######################################################################
# Automatically generated by qmake (3.0) Tue Sep 22 11:45:32 2015
######################################################################

QT+= core gui testlib
TEMPLATE = app
TARGET = qtmarkup
INCLUDEPATH += .

# Input
HEADERS += qtmarkup.h ui_qtmarkup.h
FORMS += qtmarkup.ui
SOURCES += main.cpp \
           qtmarkup.cpp \
           qtmarkup_automoc.cpp
